# Remove Escape delay
set -s escape-time 0

# Enable focus
# set -g focus-events on

# 256 color
# set -g default-terminal 'tmux-256color:RGB'
# set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-features 'foot:RGB'

# Vi for copy mode
# set -g mode-keys vi

# Scrollback buffer
set -g history-limit 10000

# Start at index 1 instead of 0
set -g base-index 1
set -g pane-base-index 1

# Re-arange windows's index
set -g renumber-windows on


# Bindings
# --------
# Rebind prefix
unbind C-b
set -g prefix M-a
# bind M-a send-prefix

# Jump to the last window
bind b last-window
# bind o last-window

# Reload
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"

# Preload session
# bind S source-file ~/.config/tmux/my-session \; display-message "Source session done!"

# Switch to 2x2 grid
# bind g select-layout tiled

# Select panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind ` select-pane -t !

# Swap between current and last active pane
bind -r S swap-pane -s ! -t !

# Swap panes horizontally/vertically
# bind L next-layout
# bind-key v if -F '#{==:#{window_panes},2}' \
#   'if -F "#{&&:#{pane_at_left},#{pane_at_right}}" \
#       "select-layout even-horizontal" \
#       "select-layout even-vertical"'

# Resize panes
# unbind '<'
# unbind '>'
bind -r '=' resize-pane -U 2
bind -r '-' resize-pane -D 2
bind -r '_' resize-pane -L 2
bind -r '+' resize-pane -R 2

# Split panes using J/L
# bind J split-window -v
# bind L split-window -h

# Scroll half page in copy-mode using Alt+u/d
bind -T copy-mode-vi 'M-u' send-keys C-u
bind -T copy-mode-vi 'M-d' send-keys C-d

# Switch windows
bind -r p select-window -t -1
bind -r n select-window -t +1

# Move windows
bind -r P swap-window -t -1\; select-window -t -1
bind -r N swap-window -t +1\; select-window -t +1

# New window after the current one
bind t new-window -a -c "$HOME"

# Theming
# -------
gray_darkest='#1c1917'
gray_dark='#342f2c'
gray_medium='#685f5a'
accent_fg=green
# NOTE: Set bg=default to enable transparent
accent_bg=default

# Status
set -g status on # 2/on
# set -g status-format[1] ""
# set -g status-format[1] "#[fg=default]"
set -g status-position top
set -g status-justify absolute-centre # absolute-centre
set -g status-style bg=$accent_bg,fg=brightblack
set -g status-left '#[fg=default]#S'
set -g status-right '#[fg=default]%d-%m #[fg=green bold]%H:%M' # %a %d-%h(%m)-%y'
# set -g window-status-current-format '[#[fg=default]#I:#[fg=$accent_fg]#W]'
set -g window-status-style bg=$accent_bg,fg=default
# set -g window-status-current-style bg=$accent_bg,fg=$accent_fg
set -g window-status-current-style bg=default,fg=green,bold

# Message/highlight
set -g message-style bg=$accent_fg,fg=black
set -g mode-style bg=$accent_fg,fg=black

# Border
set -g pane-active-border-style bg=default,fg=$accent_fg
set -g pane-border-style bg=default,fg=brightblack

# Clock
set -g clock-mode-color brightblack


# TPM
# ---
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Save and reload tmux windows
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents off

# Tmux ez mode
#set -g @tmux-which-key-disable-autobuild=1
set -g @plugin 'alexwforsythe/tmux-which-key'

# Init TPM
run '~/.config/tmux/plugins/tpm/tpm'
