[main]
# THE PIXEL PERFECT WAY
# --------------------------------------------------------------------
# [Constraint] pixelsize > 15
# Height: 20px | Width: 12px (Standard 0.6 ratio)
# [Constraint] Respect adjustment, not drastic.
# Steps: 25 -> 30
# Every zoom level lands on a clean integer width (15px -> 18px).
#font=jetbrains mono:pixelsize=25:weight=medium
#font-size-adjustment=5
#dpi-aware=yes
# --------------------------------------------------------------------

# THE LAZY WAY
# --------------------------------------------------------------------
# Font is render as is, then got upscaled by the compositor.
# E.g 15pt x 1.333(96 DPI convert standard) x 1.25 (compositor) = ~25px
# Steps: 15 -> 18 -> 21
# font=jetbrains mono:size=15:weight=medium
font=iosevka me:size=18:weight=medium
font-size-adjustment=3
dpi-aware=no
# --------------------------------------------------------------------

# [Constraint] Pad >= 4
# Horizontal Pad: 4, 12, 16 (Logical) -> 5, 15, 20 px (Physical)
# Vertical Pad: 4, 8, 12 (Logical) -> 5, 10, 15 px (Physical)
pad=0x0 center

initial-window-size-chars=80x24
bold-text-in-bright=palette-based # palette-based
#gamma-correct-blending=yes

# TESTING: sharp borders in TUI for niri fractional scaling
# box-drawings-uses-font-glyphs=no

# 20px (logical) * 1.25 = 25px (physical). A perfect integer grid.
#line-height=20

[scrollback]
lines=10000
multiplier=4.0
indicator-format=percentage # line # percentage
indicator-position=fixed

[colors-dark]
background=0a1a18 #0e0d0d #131313 #181818
foreground=baab7c #b6bfc4 #baab76 #bcad78

regular0=0a1a18   #221f1e #131514
regular1=bb7744   #d05a5b #d36d64 #bb7744
regular2=5f875f   #8aa260 #788e53 #5f875f
regular3=c9a554   #d79174 #ce9178 #ce9c78 #c79c74 #c9a554
regular4=6b7a5d   #5ca5cf         #7f8a50
regular5=907556   #9c925f #9e704c #a27a52 #907556 #9e784c #90744f
regular6=7f8a50   #37ada4 #559da0 #6b826e #91947e #6b7a5d
regular7=9c925f   #908883         #b8b488

bright0=5e5850    #697257 #686e5d #5e5850
bright1=bb7744    #bb7744         #d68d5e
bright2=5f875f    #7f8a50         #a9b665 #9db070
bright3=c9a554    #c9a554         #e2bb7d #d8a657
bright4=6b7a5d    #5f875f                 #8ea48e
bright5=907556    #77644c         #7da37d #92ad6a
bright6=7f8a50    #aca169         #a9c1a9 #9ca67d
bright7=baab7c    #baab76 #c5c2a5

# alpha=0.85
blur=yes

[key-bindings]
scrollback-up-page=Mod1+bracketleft
scrollback-down-page=Mod1+bracketright
scrollback-up-half-page=Mod1+u
scrollback-down-half-page=Mod1+d
scrollback-down-line=Mod1+j
scrollback-up-line=Mod1+k
#show-urls-launch=Control+Shift+u
show-urls-copy=Control+Shift+u
unicode-input=none
quit=Super+q

[search-bindings]
find-prev=Control+p
find-next=Control+n

[cursor]
# TESTING: for niri fractional scaling
# beam-thickness=2
underline-thickness=2px
