[main]
# THE PIXEL PERFECT WAY
# --------------------------------------------------------------------
# [Constraint] pixelsize > 15
# Height: 20px | Width: 12px (Standard 0.6 ratio)
# [Constraint] Respect adjustment, not drastic.
# Steps: 25 -> 30
# Every zoom level lands on a clean integer width (15px -> 18px).
#font=jetbrains mono:pixelsize=25:weight=medium
#font-size-adjustment=5
#dpi-aware=yes
# --------------------------------------------------------------------

# THE LAZY WAY
# --------------------------------------------------------------------
# Font is render as is, then got upscaled by the compositor.
# E.g 15pt x 1.333(96 DPI convert standard) x 1.25 (compositor) = ~25px
# Steps: 15 -> 18 -> 21
# font=jetbrains mono:size=15:weight=medium
font=iosevka me:size=18:weight=medium
font-size-adjustment=3
dpi-aware=no
# --------------------------------------------------------------------

# [Constraint] Pad >= 4
# Horizontal Pad: 4, 12, 16 (Logical) -> 5, 15, 20 px (Physical)
# Vertical Pad: 4, 8, 12 (Logical) -> 5, 10, 15 px (Physical)
pad=0x0 center

initial-window-size-chars=80x24
bold-text-in-bright=palette-based # palette-based
#gamma-correct-blending=yes

# TESTING: sharp borders in TUI for niri fractional scaling
# box-drawings-uses-font-glyphs=no

# 20px (logical) * 1.25 = 25px (physical). A perfect integer grid.
#line-height=20

[scrollback]
lines=10000
multiplier=4.0
indicator-format=percentage # line # percentage
indicator-position=fixed

[colors-dark]
background=0a1a18 #0e0d0d #131313 #181818
background=101d1a #101d1a
foreground=b6a677 #b6a677

regular0=122220   #122220
regular1=bb7744   #bb7744
regular2=5f875f   #5f875f
regular3=bc9c52   #bc9c52
regular4=7c8b6d   #7c8b6d
regular5=846e52   #846e52
regular6=808a51   #808a51
regular7=968a69   #a69b65

bright0=68685a    #666059
bright1=bb7744    #bb7744
bright2=5f875f    #5f875f
bright3=bc9c52    #c4a45a
bright4=7c8b6d    #7c8b6d
bright5=846e52    #846e52
bright6=808a51    #808a51
bright7=b6a677    #b6a677

# alpha=0.85
blur=yes

[key-bindings]
scrollback-up-page=Mod1+bracketleft
scrollback-down-page=Mod1+bracketright
scrollback-up-half-page=Mod1+u
scrollback-down-half-page=Mod1+d
scrollback-down-line=Mod1+j
scrollback-up-line=Mod1+k
#show-urls-launch=Control+Shift+u
show-urls-copy=Control+Shift+u
unicode-input=none
quit=Super+q

[search-bindings]
find-prev=Control+p
find-next=Control+n

[cursor]
# TESTING: for niri fractional scaling
# beam-thickness=2
underline-thickness=2px
